### ISSUE TITLE
Error fetching test candidates: org/eclipse/jdt/ls/core/internal/hover/JavaElementLabels

### ISSUE THREAD

**Issue by Delice0** [mfussenegger/nvim-jdtls#570] opened 2023-10-11 20:18 UTC
### LSP client configuration

I'm using the default configuration from LazyVim.

### Eclipse.jdt.ls version

v1.28.0                                   

### Steps to Reproduce

go to test file and try to run test using the following:

* Run nearest test
* Run all test
* Run test

### Expected Result

I expect that the test(s) runs

### Actual Result

Error fetching test candidates: org/eclipse/jdt/ls/core/internal/hover/JavaElementLabels

**Comment by mfussenegger** [comment] 2023-10-12 08:03
Duplicate of https://github.com/mfussenegger/nvim-jdtls/issues/565

**Closed by mfussenegger** 2023-10-12 08:03 UTC
