### ISSUE TITLE
Java specified by path doesn't work.

### ISSUE THREAD

**Issue by BodeaPeGitHub** [mfussenegger/nvim-jdtls#549] opened 2023-09-05 08:05 UTC
### LSP client configuration

local config = {
  cmd = {

    'C:\\Users\\BodeaPeGitHub\\apps\\jdk-20.0.2\\bin\\java',
    '-Declipse.application=org.eclipse.jdt.ls.core.id1',
    '-Dosgi.bundles.defaultStartLevel=4',
    '-Declipse.product=org.eclipse.jdt.ls.core.product',
    '-Dlog.protocol=true',
    '-Dlog.level=ALL',
    '-Xmx1g',
    '--add-modules=ALL-SYSTEM',
    '--add-opens', 'java.base/java.util=ALL-UNNAMED',
    '--add-opens', 'java.base/java.lang=ALL-UNNAMED',
    '-jar', 'C:\\Users\\BodeaPeGitHub\\AppData\\Local\\nvim-data\\mason\\packages\\jdtls\\plugins\\org.eclipse.equinox.launcher_1.6.500.v20230717-2134.jar',
    '-configuration', 'C:\\Users\\BodeaPeGitHub\\AppData\\Local\\nvim-data\\mason\\packages\\jdtls\\config_win',
    '-data', workspace_dir,
  },
}

require('jdtls').start_or_attach(config)
```

### Eclipse.jdt.ls version

Last one, just cloned the repository.

### Steps to Reproduce

Set JAVA_HOME variable to refer a Java 8 and set the java path into the config file.

### Expected Result

It should work just fine.

### Actual Result

```
	[ERROR][2023-09-05 10:45:42] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\BodeaPeGitHub\\apps\\jdk-20.0.2\\bin\\java"	"stderr"	"WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.concurrent\r\n"
	[ERROR][2023-09-05 10:46:05] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\BodeaPeGitHub\\AppData\\Local\\nvim-data\\mason\\bin\\jdtls.CMD"	"stderr"	'Traceback (most recent call last):\r\n  File "C:\\\\Users\\\\sBodea\\\\AppData\\\\Local\\\\nvim-data\\\\mason\\\\packages\\\\jdtls\\\\bin/jdtls", line 17, in <module>\r\n'
	[ERROR][2023-09-05 10:46:05] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\BodeaPeGitHub\\AppData\\Local\\nvim-data\\mason\\bin\\jdtls.CMD"	"stderr"	"    jdtls.main(sys.argv[1:])\r\n"
	[ERROR][2023-09-05 10:46:05] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\BodeaPeGitHub\\AppData\\Local\\nvim-data\\mason\\bin\\jdtls.CMD"	"stderr"	'  File "C:\\Users\\sBodea\\AppData\\Local\\nvim-data\\mason\\packages\\jdtls\\bin\\jdtls.py", line 82, in main\r\n'
	[ERROR][2023-09-05 10:46:05] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\BodeaPeGitHub\\AppData\\Local\\nvim-data\\mason\\bin\\jdtls.CMD"	"stderr"	"    java_executable = get_java_executable(known_args.validate_java_version)\r\n"
	[ERROR][2023-09-05 10:46:05] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\BodeaPeGitHub\\AppData\\Local\\nvim-data\\mason\\bin\\jdtls.CMD"	"stderr"	'                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\sBodea\\AppData\\Local\\nvim-data\\mason\\packages\\jdtls\\bin\\jdtls.py", line 40, in get_java_executable\r\n'
	[ERROR][2023-09-05 10:46:05] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\BodeaPeGitHub\\AppData\\Local\\nvim-data\\mason\\bin\\jdtls.CMD"	"stderr"	'    raise Exception("jdtls requires at least Java 17")\r\n'
	[ERROR][2023-09-05 10:46:05] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\BodeaPeGitHub\\AppData\\Local\\nvim-data\\mason\\bin\\jdtls.CMD"	"stderr"	"Exception: jdtls requires at least Java 17\r\n"
```

**Comment by mfussenegger** [comment] 2023-09-05 18:01
Duplicate of https://github.com/mfussenegger/nvim-jdtls/discussions/548

**Closed by mfussenegger** 2023-09-05 18:01 UTC
