### ISSUE TITLE
Wrong script, I guess

### ISSUE THREAD

**Issue by EpsilonKu** [mfussenegger/nvim-jdtls#109] opened 2021-08-06 09:26 UTC
### LSP client configuration

	local config = {}
	config.cmd = {'jdtls.sh'}
	require ('jdtls').start_or_attach (config)

### Steps to Reproduce

I run `kabouzeid/nvim-lspinstall` script for java. And copied all downloaded files to `./local/bin/`. jdtls.sh script works good on terminal run.

### Expected Result

No error

### Actual Result

Error detected while processing /home/epsku/.config/nvim/init.lua:                                                                                                                                                   
E5113: Error while calling lua chunk: ...im/site/pack/packer/start/nvim-jdtls/lua/jdtls/setup.lua:170: Vim(write):E32: No file name

**Comment by mfussenegger** [comment] 2021-08-06 10:46
Should be fixed with https://github.com/mfussenegger/nvim-jdtls/pull/110 - the problem isn't the script, but rather that nvim-jdtls has logic to implicitly save files before launching/attaching the language server & client. This caused an error with an empty buffer.

eclipse.jdt.ls currently would choke if a buffer on a file that doesn't exist on disk is attached.

**Closed** 2021-08-06 10:51 UTC
