### ISSUE TITLE
The moved file is not indexed

### ISSUE THREAD

**Issue by JrO5YRu9mr** [mfussenegger/nvim-jdtls#173] opened 2021-11-07 11:52 UTC
### LSP client configuration

neovim-0.5.0-1

```
Plug 'neovim/nvim-lspconfig'
Plug 'mfussenegger/nvim-jdtls'

...

" nvim-jdtls
    if has('nvim-0.5')
      augroup lsp
        au!
        au FileType java lua require('jdtls').start_or_attach({cmd = {'l-jdtls.sh', '/workspace/' .. vim.fn.fnamemodify(vim.fn.getcwd(), ':p:h:t')}});
      augroup end
    endif
```

### Eclipse.jdt.ls version

v1.5.0 commit ed69aae7

### Steps to Reproduce

1.  Open neovim in the project folder (pom.xml)
2.  Starting server - ok
3.  Open java file
4.  Run `lua require('jdtls').code_action(true)`
5.  Select `1: Move 'App'...`
6.  Move to another package
7.  After the previous step, the lsp-server for this file does not work. Completion, actions, etc.

### Expected Result

Completion and actions works, etc

### Actual Result

Completion and actions don't work, etc

**Comment by mfussenegger** [comment] 2021-11-08 22:50
Thanks for the report - turned out that this is an issue with the neovim lsp client.  https://github.com/neovim/neovim/pull/16266 should fix it.

**Comment by mfussenegger** [comment] 2021-11-18 13:04
Could you try with a neovim nightly build if the problem is resolved? https://github.com/neovim/neovim/pull/16266 got merged.

**Comment by JrO5YRu9mr** [comment] 2021-11-21 13:27
Yes, I'm building from source code, everything works, thank you!

**Closed** 2021-11-21 15:13 UTC
